 -- Create SEQUENCE for order line items
CREATE SEQUENCE orderNumber
as int 
START with 1
increment by 1

CREATE TABLE OrderDetails(
    OrderLineID int primary key identity(1,1),
    OrderID bigint not null,
    OrderDate Date not null,
    ProductID int not null,
    Quantity int not null,
    UnitPrice decimal(10,2) not null,
    LineTotal as (Quantity * UnitPrice),
    CONSTRAINT fk_productID
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID),
    FOREIGN KEY (OrderId,OrderDate) REFERENCES [Order](OrderID,OrderDate),
    Check (UnitPrice > 0),
    check(Quantity > 0)

)

-- Insert three order-detail rows. The VALUES table supplies each row's
-- quantity and unit price. CROSS APPLY selects the first available order and
-- product, and the SELECT combines those values for insertion. OrderLineID
-- is generated by IDENTITY, while LineTotal is calculated automatically.
insert into OrderDetails
( OrderID, OrderDate, ProductID, Quantity, UnitPrice)
SELECT o.OrderID, o.OrderDate, p.ProductID, v.Quantity, v.UnitPrice
FROM (VALUES
    (2, 99.99),
    (1, 149.99),
    (3, 99.99)
) AS v(Quantity, UnitPrice)
CROSS APPLY (SELECT TOP (1) OrderID, OrderDate
           FROM [Order]
           ORDER BY OrderID) AS o
CROSS APPLY (SELECT TOP (1) ProductID
           FROM Product
           ORDER BY ProductID) AS p;
 GO



select * from OrderDetails


 INSERT INTO Product (ProductName, CategoryID, SupplierID, UnitPrice, UnitinStock)
 VALUES ('Invalid', 1, 1, -50, 10);