with dataseq_cte_re
as
(
select cast(DATEADD(month,datEdiff(month,0,GETDATE()),0) AS DATE ) AS FIRSTDATE
--THIS WILL RETURN FIRS T DAY OF THIS MONTH 
-- ANCHOR 
UNION ALL
SELECT  DATEADD (DAY,1,FIRSTDATE)
FROM dataseq_cte_re
WHERE FIRSTDATE < EOMONTH(GETDATE())
)
SELECT 
E.FIRSTDATE,
DATENAME(WEEKDAY,E.FIRSTDATE) AS DAYNAMEE,
DATENAME(WEEK,FIRSTDATE)

FROM dataseq_cte_re E
OPTION(MAXRECURSION 31)
