-- defualt constarints
use MYDATABASE
ALTER TABLE DEPARTMENTS
ADD STATUS VARCHAR(50) DEFAULT 'REGULAR';

SELECT *
FROM DEPARTMENTS
ALTER TABLE DEPARTMENTS
DROP CONSTRAINT 
DF__DEPARTMEN__STATU__3A4CA8FD
ALTER TABLE DEPARTMENTS
DROP COLUMN STATUS

-- 
ALTER TABLE DEPARTMENTS
ADD CONSTRAINT 
DF_DEPARTMENTS_STATUS
DEFAULT 'REGULAR' FOR STATUS


UPDATE DEPARTMENTS
SET STATUS ='REGULAR'
WHERE STATUS  IS NULL