-- OPEN JSON
-- IT IS A TABLE VALUED FUNCTION  THAT PARSES JSON TEXT AND RETURNS THE JSON DATA
-- AS RETATIONL ROWSET
SELECT * from ConfigurationData1 CROSS APPLY
OPENJSON(skills ,  ' $.Languages')  