--REPLACE
-- REPLACES SPECIFIC CHARARCTER WITH NEW CHARACTER
-- IT ASLO REMOVE WITH BLANK QOUTES
SELECT 
'123-456-678-901' AS PHONE,
REPLACE('123-456-678-901','-','*') AS PHONE_ ,
REPLACE('123-456-678-901','-','') AS PHONE_CLEAN

SELECT
'REPORT.TXT' AS OLD_EX,
LOWER(REPLACE('REPORT.TXT','.TXT','.CSV')) AS NEW_EX

SELECT
TRIM('    jOHN   '),
LEN(TRIM('    jOHN   '))